import { Product, ProductInfo, Seller } from './product.entity'

const sellers: Seller[] = [
  {
    memberId: 's1',
    companyName: '주식회사 착착',
    repName: '홍길동',
    companyPhoneNumber: '02-123-4567',
    sellerAddress: '서울특별시 강남구 테헤란로 100',
  },
  {
    memberId: 's2',
    companyName: '패션스토어',
    repName: '김영희',
    companyPhoneNumber: '02-222-3333',
    sellerAddress: '서울특별시 마포구 합정로 20',
  },
  {
    memberId: 's3',
    companyName: '디지털샵',
    repName: '이철수',
    companyPhoneNumber: '031-555-7777',
    sellerAddress: '경기도 성남시 분당구 판교역로 120',
  },
]

export const productInfos: ProductInfo[] = [
  {
    productId: 'p1',
    title: '맛있는 찰옥수수 냉동 옥수수 10개입',
    description: '달콤하고 신선한 찰옥수수, 냉동 보관으로 사계절 즐기세요.',
    images: [
      { imageId: 1, url: 'https://picsum.photos/id/1011/400/300' },
      { imageId: 2, url: 'https://picsum.photos/id/1012/400/300' },
    ],
    category: '식품',
    price: 12000,
    isCoupon: true,
    targetAmount: 200,
    presentPersonCount: 70,
    totalPrice: 12000 * 70,
    recruitmentStartPeriod: '2025-09-01',
    recruitmentEndPeriod: '2025-09-30',
    tags: [],
  },
  {
    productId: 'p2',
    title: '여름 반팔 티셔츠 3종 세트',
    description: '시원하고 세탁에도 강한 기본 반팔 티셔츠, 남녀공용.',
    images: [{ imageId: 1, url: 'https://picsum.photos/id/1015/400/300' }],
    category: '패션',
    price: 24900,
    isCoupon: false,
    targetAmount: 300,
    presentPersonCount: 210,
    totalPrice: 24900 * 210,
    recruitmentStartPeriod: '2025-08-25',
    recruitmentEndPeriod: '2025-09-20',
    tags: [],
  },
  {
    productId: 'p3',
    title: '무선 블루투스 이어폰 Pro',
    description: '최신 블루투스 5.3, 액티브 노이즈 캔슬링 탑재.',
    images: [
      { imageId: 1, url: 'https://picsum.photos/id/1021/400/300' },
      { imageId: 2, url: 'https://picsum.photos/id/1022/400/300' },
    ],
    category: '디지털/가전',
    price: 129000,
    isCoupon: false,
    targetAmount: 150,
    presentPersonCount: 120,
    totalPrice: 129000 * 120,
    recruitmentStartPeriod: '2025-09-05',
    recruitmentEndPeriod: '2025-09-28',
    tags: [],
  },
  {
    productId: 'p4',
    title: '주방용 스테인리스 냄비 세트 (3종)',
    description: '튼튼하고 오래가는 스테인리스 냄비 세트. 가정 필수템!',
    images: [{ imageId: 1, url: 'https://picsum.photos/id/1033/400/300' }],
    category: '생활/주방',
    price: 59000,
    isCoupon: true,
    targetAmount: 100,
    presentPersonCount: 42,
    totalPrice: 59000 * 42, // 2,478,000
    recruitmentStartPeriod: '2025-09-10',
    recruitmentEndPeriod: '2025-09-25',
    tags: [],
  },
  {
    productId: 'p5',
    title: '뷰티 마스크팩 20매 세트',
    description: '수분 가득, 피부 진정 효과! 매일 쓰기 좋은 마스크팩.',
    images: [
      { imageId: 1, url: 'https://picsum.photos/id/1040/400/300' },
      { imageId: 2, url: 'https://picsum.photos/id/1041/400/300' },
    ],
    category: '뷰티/헬스',
    price: 9900,
    isCoupon: true,
    targetAmount: 400,
    presentPersonCount: 260,
    totalPrice: 9900 * 260,
    recruitmentStartPeriod: '2025-09-02',
    recruitmentEndPeriod: '2025-09-18',
    tags: [],
  },
]

export const products: Product[] = [
  { seller: sellers[0], product: productInfos[0] },
  { seller: sellers[1], product: productInfos[1] },
  { seller: sellers[2], product: productInfos[2] },
  { seller: sellers[0], product: productInfos[3] },
  { seller: sellers[1], product: productInfos[4] },
]
